[build]
  functions = "netlify/functions"  # ✅ Netlify Functions 폴더 지정
  command = "npm install"  # ✅ 빌드할 때 자동으로 npm 패키지 설치
  environment = { GOOGLE_CLIENT_EMAIL = "your-email", GOOGLE_PRIVATE_KEY = "your-key" }

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
